-- MySQL Script generated by MySQL Workbench
-- Mon Dec  2 09:56:48 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tRol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tRol` (
  `rolName` VARCHAR(50) NOT NULL,
  `rolDes` VARCHAR(255) NULL,
  `admin` BIT(1) NOT NULL,
  PRIMARY KEY (`rolName`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tPermiso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tPermiso` (
  `rolName` VARCHAR(50) NOT NULL,
  `pantalla` VARCHAR(50) NOT NULL,
  `acceso` BIT(1) NOT NULL,
  `insertar` BIT(1) NOT NULL,
  `modificar` BIT(1) NOT NULL,
  `borrar` BIT(1) NOT NULL,
  PRIMARY KEY (`rolName`, `pantalla`),
  CONSTRAINT `fk_tPermiso_tRol`
    FOREIGN KEY (`rolName`)
    REFERENCES `mydb`.`tRol` (`rolName`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tUsuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tUsuario` (
  `nif` VARCHAR(50) NOT NULL,
  `password` VARCHAR(50) NOT NULL,
  `rolName` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`nif`),
  INDEX `fk_tUsuario_tRol1_idx` (`rolName` ASC) VISIBLE,
  CONSTRAINT `fk_tUsuario_tRol1`
    FOREIGN KEY (`rolName`)
    REFERENCES `mydb`.`tRol` (`rolName`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tSolucion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tSolucion` (
  `ID` INT NOT NULL,
  `Solucion` VARCHAR(50) NULL,
  `Uso` VARCHAR(250) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tMuestra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tMuestra` (
  `ID` INT NOT NULL,
  `NIF_Paciente` VARCHAR(50) NULL,
  `Cultivo` VARCHAR(50) NULL,
  `Solucion` INT NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_tMuestra_tSolucion1`
    FOREIGN KEY (`ID`)
    REFERENCES `mydb`.`tSolucion` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
